### PR TITLE
Removed numpy from the host requirements

### PR DESCRIPTION
**Pull request by aivazis**
Removed numpy from the host requirements; adding it didn't solve the cp312 problem and broke everything else

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aivazis** [comment]
@conda-forge-admin, please rerender

**Comment by aivazis** [comment]
I can't quite figure out what the right thing to do is here. The cp312 builds fail because `cmake` can't find a `numpy` installation; strangely, the other versions of python all succeed. I tried adding `numpy` as a host requirement, but that causes all the builds to fail. @rtburns-jpl, any ideas?

**Comment by rtburns-jpl** [comment]
I think this has to do with the distutils removal in python 3.12.

https://github.com/pyre/pyre/blob/57374e75c4da37f455137820ae4abe02d6c81c50/.cmake/pyre_init.cmake#L46

**Comment by rtburns-jpl** [comment]
@conda-forge-admin, please rerender

**Comment by aivazis** [comment]
it looks like lambda can no longer find a solution after adding `numpy` to the dependencies. what a mess...

**Comment by aivazis** [comment]
are we missing something basic?

**Comment by rtburns-jpl** [comment]
Well at least all the x86 builds are passing now. Do you know if the M1 builds are cross-compiled? Maybe there is something wrong with our config for cross-compilation, and that's why M1 and ppc64 are failing.

**Comment by aivazis** [comment]
yes. the arm64 targets are cross compiled

**Comment by rtburns-jpl** [comment]
The ppc64 builds are cross-compiled, so that must be the docker image for the x86_64 build system.

**Comment by aivazis** [comment]
i see

**Comment by aivazis** [comment]
Another thought: in `pyre_init.cmake`, we use `distutils` to get `PYTHON3_SUFFIX`. what do you think about replacing it with `${Python_EXECUTABLE}-config --extension-suffix`?

**Comment by rtburns-jpl** [comment]
Your minimum cmake version requirement is 3.19 so that should already be enforced

**Comment by aivazis** [comment]
it looks like all tests now pass after the latest commit. do you mind looking one more and merging the pr when you are done?

**Comment by aivazis** [comment]
so, so, so. the tests pass because no tests are actually run. i tried the cmake patch on the pyre repository and it builds but fails when running tests because the name of the extension modules is not right. i patched the pyre repo so that the cmake CI build passes, updated the recipe here, and everything is good.

**Comment by rtburns-jpl** [comment]
Awesome, thanks for finding that fix.

**Pull request merged**
